DROP TABLE IF EXISTS public.cms_elements;
DROP SEQUENCE IF EXISTS "cms_elements_id_seq";

BEGIN;

CREATE SEQUENCE IF NOT EXISTS "cms_elements_id_seq";

CREATE TABLE IF NOT EXISTS public.cms_elements (
	id bigint DEFAULT nextval('cms_elements_id_seq'::regclass) NOT NULL,
	"name" character varying(100) DEFAULT NULL::character varying,
	permission_id bigint DEFAULT 0::bigint,
	"input" character varying(30) DEFAULT NULL::character varying,
	table_name character varying(255) DEFAULT NULL::character varying,
	required boolean DEFAULT true,
	column_name character varying(255) DEFAULT NULL::character varying,
	public_table boolean DEFAULT false,
	public_panel boolean DEFAULT false,
	public_tile boolean DEFAULT false,
	data_type character varying(30) DEFAULT 'text'::character varying NOT NULL,
	alias character varying(100) DEFAULT NULL::character varying,
	ordinal integer DEFAULT NULL,
	matview character varying DEFAULT NULL::character varying,
	_post boolean DEFAULT true NOT NULL,
	_put boolean DEFAULT false NOT NULL,
	_patch boolean DEFAULT false NOT NULL,
	PRIMARY KEY(id)
);

COMMIT;

-- Insert batch #1
INSERT INTO public.cms_elements (id, name, permission_id, input, table_name, required, column_name, public_table, public_panel, public_tile, data_type, alias, ordinal, matview, _post, _put, _patch) VALUES
(1, 'license_number', 3, 'number', 'crm_establishments', 'False', 'license_number', 'True', 'True', 'True', 'integer', 'license_number', 1, 'manufacturers', 'True', 'False', 'False'),
(2, 'manufacturers', 3, 'cs', 'crm_establishments', 'False', 'name', 'True', 'True', 'True', 'text', 'manufacturer', 2, 'manufacturers', 'True', 'False', 'False'),
(3, 'establishment_types', 3, 'select', 'crm_establishments', 'True', 'establishment_type_id', 'True', 'True', 'True', 'bigint', 'manufacturer_type', 5, 'manufacturers', 'True', 'True', 'True'),
(4, 'license_types', 3, 'select', 'crm_establishments', 'True', 'license_type_id', 'True', 'True', 'True', 'bigint', 'license_type', 6, 'manufacturers', 'True', 'True', 'True'),
(5, 'license_sub_types', 3, 'select', 'crm_establishments', 'True', 'license_sub_type_id', 'True', 'True', 'False', 'bigint', 'license_sub_type', 7, 'manufacturers', 'True', 'False', 'False'),
(6, 'address', 3, 'text', 'crm_establishments', 'False', 'address', 'True', 'True', 'True', 'text', 'address', 3, 'manufacturers', 'False', 'False', 'False'),
(7, 'address', 0, 'json', 'pim_orders', 'True', 'address_id', 'False', 'True', 'True', 'object', 'street', NULL, NULL, 'True', 'False', 'False'),
(8, 'active', 3, 'boolean', 'crm_establishments', 'True', 'active', 'False', 'True', 'True', 'boolean', 'active', NULL, 'manufacturers', 'False', 'False', 'False'),
(9, 'customers', 3, 'cs', 'crm_establishments', 'True', 'name', 'True', 'True', 'True', 'text', 'customer', NULL, 'matview_customers', 'True', 'False', 'False'),
(10, 'municipalities', 3, 'select', 'sys_municipalities', 'True', 'township', 'False', 'True', 'True', 'bigint', 'city', NULL, NULL, 'True', 'False', 'False'),
(11, 'provinces', 3, 'select', 'sys_provinces', 'True', 'name_en', 'False', 'False', 'False', 'bigint', 'province', NULL, NULL, 'True', 'False', 'False'),
(12, 'street', 3, 'text', 'sys_addresses', 'True', 'street', 'True', 'True', 'True', 'text', NULL, NULL, NULL, 'True', 'False', 'False'),
(15, 'sku', 3, 'number', 'pim_batch', 'True', 'sku', 'True', 'True', 'True', 'bigint', 'sku', NULL, NULL, 'True', 'False', 'False'),
(16, 'upc', 3, 'number', 'pim_batch', 'True', 'upc', 'False', 'False', 'False', 'integer', 'upc', NULL, NULL, 'True', 'False', 'False'),
(17, 'litres_per_bottle', 3, 'number', 'pim_batch', 'True', 'litres_per_bottle', 'True', 'True', 'True', 'numeric(10,4)', 'litres_per_bottle', NULL, NULL, 'True', 'False', 'False'),
(18, 'bottles_per_skid', 3, 'number', 'pim_batch', 'False', 'bottles_per_skid', 'True', 'True', 'True', 'integer', 'bottles_per_sku', NULL, NULL, 'True', 'False', 'False'),
(19, 'alcohol_percentage', 3, 'number', 'pim_batch', 'True', 'alcohol_percentage', 'True', 'True', 'True', 'numeric(10,2)', 'alcohol_percentage', NULL, NULL, 'True', 'False', 'False'),
(20, 'litter_rate', 3, 'number', 'pim_batch', 'True', 'litter_rate', 'True', 'True', 'True', 'numeric(10,4)', 'deposit', NULL, NULL, 'True', 'False', 'False'),
(21, 'quantity', 3, 'number', 'pim_inventory', 'True', 'quantity', 'True', 'True', 'True', 'numeric(10,2)', NULL, NULL, NULL, 'True', 'False', 'False'),
(22, 'manufacturers', 3, 'select', 'pim_products', 'True', 'manufacturer_id', 'True', 'True', 'True', 'bigint', 'manufacturer', NULL, NULL, 'True', 'False', 'False'),
(23, 'bottles_per_case', 3, 'number', 'pim_batch', 'True', 'bottles_per_case', 'True', 'True', 'True', 'numeric(10,2)', 'bottles_per_case', NULL, NULL, 'True', 'False', 'False'),
(24, 'manufacturer_price', 3, 'number', 'pim_batch', 'True', 'mfr_price', 'True', 'True', 'True', 'numeric(10,2)', 'manufacturer_price', NULL, NULL, 'True', 'False', 'False'),
(25, 'retail_price', 3, 'number', 'pim_batch', 'True', 'rtl_price', 'True', 'True', 'True', 'numeric(10,2)', 'retail_price', NULL, NULL, 'True', 'False', 'False'),
(26, 'wholesale_price', 3, 'number', 'pim_batch', 'True', 'ws_price', 'False', 'False', 'False', 'numeric(10,2)', 'wholesale_price', NULL, NULL, 'True', 'False', 'False'),
(28, 'locations', 3, 'select', 'crm_locations', 'True', 'id', 'True', 'True', 'True', 'bigint', 'location', NULL, NULL, 'True', 'False', 'False'),
(29, 'establishments', 3, 'select', 'crm_locations', 'True', 'establishment_id', 'True', 'True', 'True', 'bigint', 'establishment', NULL, NULL, 'True', 'False', 'False'),
(30, 'establishment_types', 3, 'select', 'crm_locations', 'True', 'type_id', 'True', 'True', 'True', 'bigint', 'establishment_type', NULL, NULL, 'True', 'False', 'False'),
(32, 'batch_id', 3, 'text', 'pim_batch', 'False', 'batch_id', 'False', 'False', 'False', 'text', 'batch_number', NULL, NULL, 'True', 'False', 'False'),
(33, 'batch_name', 3, 'text', 'pim_batch', 'False', 'batch_name', 'False', 'False', 'False', 'text', 'batch_name', NULL, NULL, 'True', 'False', 'False'),
(34, 'id', 7, 'number', 'pim_orders', 'True', 'id', 'True', 'False', 'False', 'bigint', 'order_id', NULL, NULL, 'True', 'False', 'False'),
(35, 'udf_reference', 3, 'text', 'pim_orders', 'True', 'udf_reference', 'True', 'False', 'False', 'text', 'order_number', NULL, NULL, 'True', 'False', 'False'),
(36, 'user_id', 7, 'select', 'pim_orders', 'True', 'user_id', 'False', 'False', 'False', 'bigint', 'created_by', NULL, NULL, 'True', 'False', 'False'),
(37, 'customers', 3, 'select', 'pim_orders', 'True', 'customer_id', 'True', 'False', 'False', 'bigint', 'customer', NULL, NULL, 'True', 'False', 'False'),
(38, 'manufacturers', 6, 'select', 'pim_orders', 'True', 'manufacturer_id', 'True', 'False', 'False', 'bigint', 'manufacturer', NULL, NULL, 'True', 'False', 'False'),
(39, 'locations', 7, 'select', 'pim_orders', 'True', 'location_id', 'False', 'False', 'False', 'bigint', 'locations', NULL, NULL, 'True', 'False', 'False'),
(40, 'paid', 3, 'boolean', 'pim_orders', 'True', 'paid', 'True', 'False', 'False', 'True/False', 'paid', NULL, NULL, 'True', 'False', 'False'),
(41, 'rush', 3, 'boolean', 'pim_orders', 'True', 'rush', 'True', 'False', 'False', 'True/False', 'rush', NULL, NULL, 'True', 'False', 'False'),
(42, 'pickup', 3, 'boolean', 'pim_orders', 'True', 'pickup', 'True', 'False', 'False', 'True/False', 'pickup', NULL, NULL, 'True', 'False', 'False'),
(43, 'status', 3, 'select', 'pim_orders', 'True', 'status_id', 'True', 'False', 'False', 'bigint', 'status', NULL, NULL, 'True', 'False', 'False'),
(44, 'deliver_date', 3, 'datetime', 'pim_orders', 'True', 'delivery_date', 'True', 'False', 'False', 'timestamp without time zone', 'delivery_date', NULL, NULL, 'True', 'False', 'False'),
(45, 'create_date', 7, 'datetime', 'pim_orders', 'True', 'created', 'True', 'False', 'False', 'timestamp without time zone', 'created_date', NULL, NULL, 'True', 'False', 'False'),
(46, 'products', 0, 'json', 'pim_orders', 'False', 'products', 'False', 'False', 'False', 'object', 'product_name', NULL, NULL, 'True', 'False', 'False'),
(47, 'product', 0, 'text', 'pim_batch', 'True', 'product', 'True', 'False', 'False', 'bigint', 'product_name', NULL, NULL, 'True', 'False', 'False'),
(48, 'notes', 0, 'json', 'pim_orders', 'False', 'notes', 'False', 'False', 'False', 'object', 'notes', NULL, NULL, 'True', 'False', 'False'),
(49, 'transfer_type', 3, 'select', 'pim_transfers', 'False', 'type', 'True', 'False', 'False', 'object', 'transfer_type', NULL, NULL, 'True', 'False', 'False'),
(51, 'manufacturer', 3, 'select', 'pim_transfers', 'True', 'manufacturer_id', 'True', 'False', 'False', 'bigint', 'manufacturer', NULL, NULL, 'True', 'False', 'False'),
(52, 'from_warehouse', 3, 'select', 'pim_transfers', 'True', 'from_id', 'True', 'False', 'False', 'bigint', 'from_warehouse', NULL, NULL, 'True', 'False', 'False'),
(53, 'to_warehouse', 3, 'select', 'pim_transfers', 'True', 'to_id', 'True', 'False', 'False', 'bigint', 'to_warehouse', NULL, NULL, 'True', 'False', 'False'),
(54, 'created_by', 3, 'select', 'pim_transfers', 'True', 'user_id', 'True', 'False', 'False', 'bigint', 'created_by', NULL, NULL, 'True', 'False', 'False'),
(55, 'status', 3, 'select', 'pim_transfers', 'True', 'status_id', 'True', 'False', 'False', 'bigint', 'status', NULL, NULL, 'True', 'False', 'False'),
(56, 'transfer_type_id', 3, 'select', 'pim_transfers', 'True', 'type_id', 'True', 'False', 'False', 'bigint', 'transfer_type', NULL, NULL, 'True', 'False', 'False'),
(60, 'product_type', 3, 'select', 'pim_batch', 'True', 'product_type_id', 'False', 'False', 'False', 'bigint', 'product_type', NULL, NULL, 'True', 'False', 'False'),
(61, 'package_type', 3, 'select', 'pim_batch', 'True', 'package_type_id', 'False', 'False', 'False', 'bigint', 'package_type', NULL, NULL, 'True', 'False', 'False'),
(62, 'products', 3, 'text', 'pim_batch', 'True', 'product', 'False', 'False', 'False', 'character varying', 'product', NULL, NULL, 'True', 'False', 'False'),
(63, 'products', 3, 'json', 'pim_transfers', 'False', 'products', 'False', 'False', 'False', 'object', 'product_name', NULL, NULL, 'True', 'False', 'False'),
(64, 'create_date', 3, 'datetime', 'pim_transfers', 'True', 'created', 'True', 'False', 'False', 'timestamp witout time zone', 'created_date', NULL, NULL, 'True', 'False', 'False'),
(65, 'notes', 3, 'json', 'pim_transfers', 'False', 'notes', 'True', 'False', 'False', 'object', 'notes', NULL, NULL, 'True', 'False', 'False'),
(66, 'address', 3, 'text', NULL, 'False', NULL, 'True', 'False', 'False', 'text', 'address', NULL, NULL, 'True', 'False', 'False'),
(67, 'opens_at', 3, 'text', 'crm_establishments', 'False', 'opens', 'False', 'False', 'False', 'time', 'opens_at', NULL, 'manufacturers', 'False', 'False', 'False'),
(68, 'closes_at', 3, 'time', 'crm_establishments', 'False', 'closes', 'False', 'False', 'False', 'time', 'closes_at', NULL, 'manufacturers', 'False', 'False', 'False'),
(69, 'delivery_days', 3, 'json', 'crm_establishments', 'False', 'delivery_days', 'False', 'False', 'False', 'object', 'delivery_days', NULL, 'manufacturers', 'False', 'False', 'False'),
(70, 'notes', 0, 'json', 'crm_establishments', 'False', 'notes', 'True', 'False', 'False', 'object', 'notes', NULL, 'global', 'False', 'False', 'False'),
(72, 'store_number', 3, 'number', 'crm_establishments', 'False', 'store_number', 'True', 'False', 'False', 'integer', 'store_number', 4, 'manufacturers', 'False', 'False', 'False'),
(76, 'notes', 0, 'json', 'pim_batch', 'False', 'notes', 'False', 'False', 'False', 'object', 'notes', NULL, NULL, 'True', 'False', 'False'),
(79, 'id', 7, 'text', 'pim_transfers', 'True', 'id', 'True', 'False', 'False', 'bigint', 'transfer_id', NULL, NULL, 'True', 'False', 'False'),
(82, 'auto_invoicing', 3, 'boolean', 'crm_establishments', 'False', 'auto_invoicing', 'False', 'False', 'False', 'boolean', 'auto_invoicing', NULL, 'manufacturers', 'False', 'False', 'False');

END;