
CREATE USER dt_op_readonly WITH ENCRYPTED PASSWORD 'VHwAYsk1b1xDL8v5zVQD';
GRANT CONNECT ON DATABASE "old-portal" TO dt_op_readonly;
GRANT USAGE ON SCHEMA public TO dt_op_readonly;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO dt_op_readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA public to dt_op_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO dt_op_readonly;


CREATE USER backup_user  WITH ENCRYPTED PASSWORD 'password'; 
GRANT CONNECT ON DATABASE "v25_public" to jeff_johnson; 
GRANT USAGE ON SCHEMA public to jeff_johnson; /*thanks Dominic!*/ 
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO jeff_johnson; 
GRANT SELECT ON ALL TABLES IN SCHEMA public TO jeff_johnson; 


CREATE USER dev_ricky WITH ENCRYPTED PASSWORD 'VHwAYsk1b1xDL8v5zVQD';
GRANT CONNECT ON DATABASE "v25_development" TO dev_ricky;
GRANT USAGE ON SCHEMA public to dev_ricky;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO dev_ricky; 
GRANT SELECT ON ALL TABLES IN SCHEMA public TO dev_ricky; 
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO dev_ricky;

CREATE USER dev_jehan WITH ENCRYPTED PASSWORD 'VHwAYsk1b1xDL8v5zVQD';
GRANT CONNECT ON DATABASE "v25_development" TO dev_jehan;
GRANT USAGE ON SCHEMA public to dev_jehan;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO dev_jehan; 
GRANT SELECT ON ALL TABLES IN SCHEMA public TO dev_jehan; 
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO dev_jehan;

CREATE USER dev_kaly WITH ENCRYPTED PASSWORD 'VHwAYsk1b1xDL8v5zVQD';
GRANT CONNECT ON DATABASE "v25_development" TO dev_kaly;
GRANT USAGE ON SCHEMA public to dev_kaly;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO dev_kaly; 
GRANT SELECT ON ALL TABLES IN SCHEMA public TO dev_kaly; 
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO dev_kaly;