DROP TABLE IF EXISTS public.cms_elements;
DROP SEQUENCE IF EXISTS public.cms_elements_id_seq;

BEGIN;

	CREATE SEQUENCE IF NOT EXISTS public.cms_elements_id_seq START 1;
	
	CREATE TABLE IF NOT EXISTS public.cms_elements (
		id bigint DEFAULT nextval('cms_elements_id_seq'::regclass) NOT NULL,
		"name" character varying(255) DEFAULT NULL,
		permission_id bigint DEFAULT NULL,
		"input" character varying(255) DEFAULT NULL::character varying,
		table_name character varying(255) DEFAULT NULL::character varying,
		required boolean DEFAULT true,
		column_name character varying(255) DEFAULT NULL::character varying,
		public_table boolean DEFAULT false,
		public_panel boolean DEFAULT false,
		public_tile boolean DEFAULT false,
		data_type character varying(255) DEFAULT 'text'::character varying NOT NULL,
		alias character varying(255) DEFAULT NULL::character varying,
		view_name character varying DEFAULT NULL::character varying,
		ordinal integer DEFAULT NULL,
		cs character varying DEFAULT NULL::character varying,
		_post boolean DEFAULT true,
		_put boolean DEFAULT true,
		_patch boolean DEFAULT true,
		_get boolean DEFAULT true,
		PRIMARY KEY(id)
	);
	
	-- Insert batch #1
	INSERT INTO public.cms_elements (id, name, permission_id, input, table_name, required, column_name, public_table, public_panel, public_tile, data_type, alias, view_name, ordinal, cs, _post, _put, _patch, _get) VALUES
		(1, 'license_number', 7, 'number', 'crm_establishments', 'False', 'license_number', 'True', 'True', 'True', 'integer', 'license_number', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(2, 'manufacturers', 3, 'text', 'crm_establishments', 'True', 'name', 'True', 'True', 'True', 'text', 'manufacturer', 'manufacturers', 0, NULL, 'True', 'True', 'True', 'True'),
		(3, 'establishment_types', 3, 'select', 'crm_establishments', 'True', 'establishment_type_id', 'False', 'True', 'True', 'bigint', 'establishment_type', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(4, 'license_types', 3, 'select', 'crm_establishments', 'True', 'license_type_id', 'True', 'True', 'True', 'bigint', 'license_type', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(5, 'license_sub_types', 3, 'select', 'crm_establishments', 'True', 'license_sub_type_id', 'True', 'True', 'True', 'bigint', 'license_sub_type', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(6, 'address', 0, 'json', 'pim_orders', 'True', 'address_id', 'False', 'False', 'False', 'object', 'street', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(7, 'license_number', 7, 'number', 'crm_establishments', 'True', 'agent_number', 'True', 'True', 'True', 'bigint', 'license_number', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(8, 'active', 7, 'boolean', 'crm_establishments', 'True', 'active', 'False', 'True', 'True', 'true/false', 'active', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(9, 'customers', 3, 'text', 'crm_establishments', 'True', 'name', 'True', 'True', 'True', 'text', 'customer', 'customers', 0, NULL, 'True', 'True', 'True', 'True'),
		(10, 'municipalities', 3, 'select', 'sys_municipalities', 'True', 'township', 'False', 'True', 'True', 'bigint', 'city', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(11, 'provinces', 3, 'select', 'sys_provinces', 'True', 'name_en', 'False', 'False', 'False', 'bigint', 'province', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(12, 'street', 3, 'text', 'sys_addresses', 'True', 'street', 'True', 'True', 'True', 'text', NULL, NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(13, 'zipcode', 3, 'text', 'crm_establishments', 'True', 'zipcode', 'True', 'True', 'True', 'text', 'postal_code', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(15, 'sku', 3, 'number', 'pim_batch', 'True', 'sku', 'True', 'True', 'True', 'bigint', 'sku', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(16, 'upc', 3, 'number', 'pim_batch', 'True', 'upc', 'False', 'False', 'False', 'integer', 'upc', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(17, 'litres_per_bottle', 3, 'number', 'pim_batch', 'True', 'litres_per_bottle', 'True', 'True', 'True', 'numeric(10,4)', 'litres_per_bottle', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(18, 'bottles_per_skid', 3, 'number', 'pim_batch', 'False', 'bottles_per_skid', 'True', 'True', 'True', 'integer', 'bottles_per_sku', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(19, 'alcohol_percentage', 3, 'number', 'pim_batch', 'True', 'alcohol_percentage', 'True', 'True', 'True', 'numeric(10,2)', 'alcohol_percentage', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(20, 'litter_rate', 3, 'number', 'pim_batch', 'True', 'litter_rate', 'True', 'True', 'True', 'numeric(10,4)', 'deposit', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(21, 'quantity', 3, 'number', 'pim_inventory', 'True', 'quantity', 'True', 'True', 'True', 'numeric(10,2)', NULL, NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(22, 'manufacturers', 3, 'select', 'pim_products', 'True', 'manufacturer_id', 'True', 'True', 'True', 'bigint', 'manufacturer', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(23, 'bottles_per_case', 3, 'number', 'pim_batch', 'True', 'bottles_per_case', 'True', 'True', 'True', 'numeric(10,2)', 'bottles_per_case', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(24, 'manufacturer_price', 3, 'number', 'pim_batch', 'True', 'mfr_price', 'True', 'True', 'True', 'numeric(10,2)', 'manufacturer_price', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(25, 'retail_price', 3, 'number', 'pim_batch', 'True', 'rtl_price', 'True', 'True', 'True', 'numeric(10,2)', 'retail_price', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(26, 'wholesale_price', 3, 'number', 'pim_batch', 'True', 'ws_price', 'False', 'False', 'False', 'numeric(10,2)', 'wholesale_price', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(28, 'locations', 3, 'select', 'crm_locations', 'True', 'id', 'True', 'True', 'True', 'bigint', 'location', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(29, 'establishments', 3, 'select', 'crm_locations', 'True', 'establishment_id', 'True', 'True', 'True', 'bigint', 'establishment', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(30, 'establishment_types', 3, 'select', 'crm_locations', 'True', 'type_id', 'True', 'True', 'True', 'bigint', 'establishment_type', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(32, 'batch_id', 3, 'text', 'pim_batch', 'False', 'batch_id', 'False', 'False', 'False', 'text', 'batch_number', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(33, 'batch_name', 3, 'text', 'pim_batch', 'False', 'batch_name', 'False', 'False', 'False', 'text', 'batch_name', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(34, 'id', 7, 'number', 'pim_orders', 'True', 'id', 'True', 'False', 'False', 'bigint', 'order_id', NULL, 0, NULL, 'False', 'False', 'False', 'True'),
		(35, 'udf_reference', 3, 'text', 'pim_orders', 'True', 'udf_reference', 'True', 'False', 'False', 'text', 'order_reference', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(36, 'user_id', 7, 'select', 'pim_orders', 'True', 'user_id', 'False', 'False', 'False', 'bigint', 'created_by', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(37, 'customers', 3, 'cs', 'pim_orders', 'True', 'customer_id', 'True', 'False', 'False', 'bigint', 'customer', NULL, 0, 'customers', 'True', 'True', 'True', 'True'),
		(38, 'manufacturers', 6, 'cs', 'pim_orders', 'True', 'manufacturer_id', 'True', 'False', 'False', 'bigint', 'manufacturer', NULL, 0, 'manufacturers', 'True', 'True', 'True', 'True'),
		(39, 'locations', 7, 'select', 'pim_orders', 'True', 'location_id', 'False', 'False', 'False', 'bigint', 'locations', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(40, 'paid', 3, 'boolean', 'pim_orders', 'True', 'paid', 'True', 'False', 'False', 'True/False', 'paid', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(41, 'rush', 3, 'boolean', 'pim_orders', 'True', 'rush', 'True', 'False', 'False', 'True/False', 'rush', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(42, 'pickup', 3, 'boolean', 'pim_orders', 'True', 'pickup', 'True', 'False', 'False', 'True/False', 'pickup', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(43, 'status', 3, 'select', 'pim_orders', 'True', 'status_id', 'True', 'False', 'False', 'bigint', 'status', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(44, 'deliver_date', 3, 'datetime', 'pim_orders', 'True', 'delivery_date', 'True', 'False', 'False', 'timestamp without time zone', 'delivery_date', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(45, 'create_date', 7, 'datetime', 'pim_orders', 'True', 'created', 'True', 'False', 'False', 'timestamp without time zone', 'created_date', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(46, 'products', 0, 'json', 'pim_orders', 'False', 'products', 'False', 'False', 'False', 'object', 'product_name', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(47, 'product', 0, 'text', 'pim_batch', 'True', 'product', 'True', 'False', 'False', 'bigint', 'product_name', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(48, 'notes', 0, 'json', 'pim_orders', 'False', 'notes', 'False', 'False', 'False', 'object', 'notes', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(49, 'transfer_type', 3, 'select', 'pim_transfers', 'False', 'type', 'True', 'False', 'False', 'object', 'transfer_type', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(51, 'manufacturer', 3, 'select', 'pim_transfers', 'True', 'manufacturer_id', 'True', 'False', 'False', 'bigint', 'manufacturer', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(52, 'from_warehouse', 3, 'select', 'pim_transfers', 'True', 'from_id', 'True', 'False', 'False', 'bigint', 'from_warehouse', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(53, 'to_warehouse', 3, 'select', 'pim_transfers', 'True', 'to_id', 'True', 'False', 'False', 'bigint', 'to_warehouse', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(54, 'created_by', 3, 'select', 'pim_transfers', 'True', 'user_id', 'True', 'False', 'False', 'bigint', 'created_by', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(55, 'status', 3, 'select', 'pim_transfers', 'True', 'status_id', 'True', 'False', 'False', 'bigint', 'status', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(56, 'transfer_type_id', 3, 'select', 'pim_transfers', 'True', 'type_id', 'True', 'False', 'False', 'bigint', 'transfer_type', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(60, 'product_type', 3, 'select', 'pim_batch', 'True', 'product_type_id', 'False', 'False', 'False', 'bigint', 'product_type', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(61, 'package_type', 3, 'select', 'pim_batch', 'True', 'package_type_id', 'False', 'False', 'False', 'bigint', 'package_type', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(62, 'products', 3, 'text', 'pim_batch', 'True', 'product', 'False', 'False', 'False', 'character varying', 'product', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(63, 'products', 3, 'json', 'pim_transfers', 'False', 'products', 'False', 'False', 'False', 'object', 'product_name', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(64, 'create_date', 3, 'datetime', 'pim_transfers', 'True', 'created', 'True', 'False', 'False', 'timestamp witout time zone', 'created_date', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(65, 'notes', 3, 'json', 'pim_transfers', 'False', 'notes', 'True', 'False', 'False', 'object', 'notes', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(66, 'address', 3, 'text', NULL, 'False', NULL, 'True', 'False', 'False', 'text', 'address', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(67, 'opens_at', 3, 'text', 'crm_establishments', 'False', 'opens', 'False', 'False', 'False', 'time', 'opens_at', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(68, 'closes_at', 3, 'time', 'crm_establishments', 'False', 'closes', 'False', 'False', 'False', 'time', 'closes_at', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(69, 'delivery_days', 3, 'json', 'crm_establishments', 'True', 'delivery_days', 'True', 'False', 'False', 'object', 'delivery_days', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(70, 'notes', 0, 'json', 'crm_establishments', 'True', 'notes', 'True', 'False', 'False', 'object', 'notes', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(72, 'store_number', 3, 'number', 'crm_establishments', 'True', 'store_number', 'True', 'False', 'False', 'integer', 'store_number', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(73, 'street', 3, 'text', 'crm_establishments', 'True', 'address_id', 'False', 'False', 'False', 'text', 'address', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(74, 'city', 7, 'select', 'crm_establishments', 'True', 'city_id', 'True', 'False', 'False', 'bigint', 'city', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(76, 'notes', 0, 'json', 'pim_batch', 'True', 'notes', 'False', 'False', 'False', 'object', 'notes', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(78, 'transfer_id', 7, 'text', 'crm_establishments', 'True', 'id', 'True', 'False', 'False', 'bigint', 'transfer_id', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(79, 'id', 7, 'text', 'pim_transfers', 'True', 'id', 'True', 'False', 'False', 'bigint', 'transfer_id', NULL, 0, NULL, 'True', 'True', 'True', 'True'),
		(80, 'auto_invoicing', 3, 'boolean', 'crm_establishments', 'True', 'auto_invoicing', 'False', 'False', 'False', 'boolean', 'auto_invoicing', NULL, 0, NULL, 'True', 'True', 'True', 'True');

COMMIT;

END;