REFRESH MATERIALIZED VIEW matview_addresses;
REFRESH MATERIALIZED VIEW matview_bc_municipalities;
REFRESH MATERIALIZED VIEW matview_cda_provinces;
REFRESH MATERIALIZED VIEW matview_customers;
REFRESH MATERIALIZED VIEW matview_locations;
REFRESH MATERIALIZED VIEW matview_manufacturers;
REFRESH MATERIALIZED VIEW matview_products;
REFRESH MATERIALIZED VIEW matview_orders;
REFRESH MATERIALIZED VIEW matview_transfers;